apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pipeline-gmsk2-run
spec:
  workspaces:
    - name: pipeline-ws
      persistentVolumeClaim:
        claimName: example-local-claim
    - name: docker-credentials
      secret:
        secretName: docker-credentials
  pipelineRef:
    name: workspace-pipeline7-ref
